### ISSUE TITLE
Cleaning up the notebook

### ISSUE THREAD

**Issue by luisortizuriarte** [Godesh/SST-analysis#2]
You left a lot of "stuff" in your notebook that is not useful. A lot of text that you can get rid of to help make your submission more understandable.

**Comment by Godesh** [comment]
The file has been cleaned nicely, and the code has been enhanced too. I am having trouble committing these changes though. If I wount succeed I will schedule a session.

**Comment by Godesh** [comment]
I have amended the file and code as well and made another initial commit. File name HWtwob_Leslie.ipynb

**Comment by luisortizuriarte** [comment]
Great! Closing issue.
